### ISSUE TITLE
Issue with processing regenerator-runtime?

### ISSUE THREAD

**Issue by dbashford** [pzuraq/ember-cli-babel-polyfills#9]
Stab in the dark on the title.

When running this code

```js
module.exports = class TransformAmd extends Filter {
  processString(contents, relativePath) {
    let file = path.basename(relativePath);

    if (DEFINE_REGEXP.test(contents) === false) {
      throw new Error(`ember-cli-babel-polyfills: unable to remap: ${file}`);
    }
```

That `Error` gets throw.

It is processing regenerator-runtime at the time, and when I print out the contents, it looks like this

```js
define(['exports', 'core-js/stable'], function (exports, stable) { 'use strict';
  stable = stable && stable.hasOwnProperty('default') ? stable['default'] : stable;
 ...
```

`DEFINE_REGEXP` doesn't match that `define` statement. I'm sure I'm doing something wrong somewhere, but I sort of have no idea where to start.

**Comment by pzuraq** [comment]
I don't think you should have to add `core-js` yourself, that definitely seems like a bug, will dig in. Was this for an addon or an app?
